version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  kibana:
   depends_on:
     - elasticsearch
   image: docker.elastic.co/kibana/kibana:8.9.0
   ports:
     - 5601:5601